const actions = {
	// Root
	WIPE_APP: 'WIPE_APP',

	// Wallet
	UPDATE_WALLET: 'UPDATE_WALLET',
	UPDATE_HEADER: 'UPDATE_HEADER',
	UPDATE_WALLET_BALANCE: 'UPDATE_WALLET_BALANCE',
	CREATE_WALLET: 'CREATE_WALLET',
	RESET_WALLET_STORE: 'RESET_WALLET_STORE',
	RESET_SELECTED_WALLET: 'RESET_SELECTED_WALLET',
	RESET_EXCHANGE_RATES: 'RESET_EXCHANGE_RATES',
	SETUP_ON_CHAIN_TRANSACTION: 'SETUP_ON_CHAIN_TRANSACTION',
	DELETE_ON_CHAIN_TRANSACTION: 'DELETE_ON_CHAIN_TRANSACTION',
	UPDATE_SEND_TRANSACTION: 'UPDATE_SEND_TRANSACTION',
	RESET_SEND_TRANSACTION: 'RESET_SEND_TRANSACTION',
	ADD_BOOSTED_TRANSACTION: 'ADD_BOOSTED_TRANSACTION',
	UPDATE_ADDRESS_INDEX: 'UPDATE_ADDRESS_INDEX',
	UPDATE_SELECTED_ADDRESS_TYPE: 'UPDATE_SELECTED_ADDRESS_TYPE',
	ADD_ADDRESSES: 'ADD_ADDRESSES',
	RESET_ADDRESSES: 'RESET_ADDRESSES',
	UPDATE_UTXOS: 'UPDATE_UTXOS',
	UPDATE_TRANSACTIONS: 'UPDATE_TRANSACTIONS',
	RESET_TRANSACTIONS: 'RESET_TRANSACTIONS',
	ADD_UNCONFIRMED_TRANSACTIONS: 'ADD_UNCONFIRMED_TRANSACTIONS',
	UPDATE_UNCONFIRMED_TRANSACTIONS: 'UPDATE_UNCONFIRMED_TRANSACTIONS',
	REPLACE_IMPACTED_ADDRESSES: 'REPLACE_IMPACTED_ADDRESSES',

	// Lightning
	UPDATE_LIGHTNING: 'UPDATE_LIGHTNING',
	UPDATE_LIGHTNING_NODE_ID: 'UPDATE_LIGHTNING_NODE_ID',
	UPDATE_LIGHTNING_CHANNELS: 'UPDATE_LIGHTNING_CHANNELS',
	UPDATE_LIGHTNING_NODE_VERSION: 'UPDATE_LIGHTNING_NODE_VERSION',
	SAVE_LIGHTNING_PEER: 'SAVE_LIGHTNING_PEER',
	REMOVE_LIGHTNING_PEER: 'REMOVE_LIGHTNING_PEER',
	UPDATE_CLAIMABLE_BALANCE: 'UPDATE_CLAIMABLE_BALANCE',
	RESET_LIGHTNING_STORE: 'RESET_LIGHTNING_STORE',
	UPDATE_LDK_ACCOUNT_VERSION: 'UPDATE_LDK_ACCOUNT_VERSION',

	// Backup
	BACKUP_UPDATE: 'BACKUP_UPDATE',
	RESET_BACKUP_STORE: 'RESET_BACKUP_STORE',
	BACKUP_SEEDER_CHECK_START: 'BACKUP_SEEDER_CHECK_START',
	BACKUP_SEEDER_CHECK_END: 'BACKUP_SEEDER_CHECK_END',

	// Todos
	RESET_TODOS: 'RESET_TODOS',
	HIDE_TODO: 'HIDE_TODO',
	RESET_HIDDEN_TODOS: 'RESET_HIDDEN_TODOS',
	CHANNEL_NOTIFICATION_SHOWN: 'CHANNEL_NOTIFICATION_SHOWN',
};

export default actions;
